### ISSUE TITLE
Secrets should be more tightly knit into Builders

### ISSUE THREAD

**Issue by milescrabill** [taskcluster/monopacker#41]
Right now secrets are more or less an afterthought - a YAML file specifies secret locations and values, and they are dumped onto the filesystem.

The issue is that we re-use builders for multiple deployment environments. For example, level 1 builders (untrusted) in firefox-ci-tc use the same `docker_worker_gcp` builder as the community-tc deployment. The difference comes when baking the image, when the secrets file is specified.

This presents an opportunity for user error, if the secrets file is incorrectly specified, the wrong secrets are used for the wrong environment, etc.

We should tie secrets more closely to builders, and consider having a builder per environment / deployment. We already sort of do this with the trusted / L3 builder. Secrets could become part of the builder config, and a builder could specify a filename key with an expected secrets mapping.

This would translate fairly well to password stores like `sops` and `pass` which store files on disk, and we could support decryption options so that decrypted secrets don't have to be stored on disk to use with monopacker.

So, instead of passing `SECRETS_FILE=/path/to/secrets`, the secrets file to use would be configured for the builder, and a root secrets directory and decryption command would be configured on the command line, i.e. `SECRETS_STORE=~/.password-store/docker-worker/yaml/`

This is still an idea, but I think it would help address a pain point with monopacker as it stands.

**Comment by djmitche** [comment]
From https://github.com/taskcluster/taskcluster/projects/9:
---
Secrets should be per-builder, rather than global to all builders.

Secrets handling in tc-admin might be a good example.

Operations that require secrets should fail if they are not present (for example, I just accidentally built images without secrets)

**Comment by Bensoto22** [comment]
{"EnvVersion":"2.0","Fields":{"code":422,"incidentId":"2441a83a-0255-46c5-9018-f243daff0bb6","message":"No commit found for SHA: main","method":"latest","name":"HttpError","stack":"HttpError: No commit found for SHA: main\n    at /app/node_modules/@octokit/request/dist-node/index.js:86:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)","status":422,"v":1},"Hostname":"taskcluster-github-web-566f99f899-vlkzc","Logger":"taskcluster.github.api","Pid":1,"Severity":3,"Timestamp":1670501952432000000,"Type":"monitor.error","message":"HttpError: No commit found for SHA: main\n    at /app/node_modules/@octokit/request/dist-node/index.js:86:21\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)","requestId":"5c375a20-c6cf-456a-a8fd-b2c93f266b3a","serviceContext":{"service":"github","version":"45.0.0"},"severity":"ERROR","traceId":"79a7e597-a91c-4cc2-8468-667e734d3798"}

**Comment by Bensoto22** [comment]
Here we gooo
